# Header
menu:
  Home: /
  Archives: /archives
  RSS: /atom.xml

# show posts nav button at post footer
post_nav: true

## show toc
# toc: true

## enable disqus powered comment system
# disqus_shortname: terminal-ninja

## enable view source, only github repo supported
# source_repo: https://github.com/haishanh/terminal/blob/master

# description: You should place your <strong>description</strong> of your site here

## this will display at the bottom of the footer
# footer: <span>&copy;</span> 2016 John Doe<br>Documentation licensed under <a href="http://creativecommons.org/licenses/by/4.0/" target="_blank">CC BY 4.0</a>.
