# Header
menu:
  Home: /
  Archives: /archives
  RSS: /atom.xml

# show posts nav button at post footer
post_nav: true

# show toc
# enable_toc: true

# description: You should place your <strong>description</strong> of your site here
